services:
  backend:
    build:
      context: ../levise-backend
      dockerfile: Dockerfile
    ports:
      - "8002:8000"
    env_file:
      - ../levise-backend/.env
    environment:
      - ALLOWED_HOSTS=localhost,127.0.0.1,backend
      - CORS_ALLOWED_ORIGINS=http://46.224.53.105:3002
    command: >
      sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3002:3000"
    environment:
      - API_BASE_URL=http://localhost:8002
    depends_on:
      - backend
